on: [push]

jobs:
  action:
    runs-on: ubuntu-latest
    name: Action Self-Test
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Policy validator
        id: test
        # uses: StephenKing/terraform-iam-policy-validator-action@v1
        uses: ./
        with:
          template-path: 'test/tfplan.json'
      # Use the output from the `hello` step
      - name: Get the output time
        run: echo "The time was ${{ steps.hello.outputs.time }}"
